### ISSUE TITLE
Getting error when using /api

### ISSUE THREAD

**Issue by el-guero-mero** [wingkee98/shorten-url#1]
Hello Kevin, this is Mateo! I'm getting an error when hitting /api (when I hit the "Go" button in the interface). 

I have the server running on port 9000, and used "npm start" after having installed all of the dependencies using "npm install". I'm getting this in Chrome browser (screenshot attached).

Any advice? Did I miss something in the instructions?

![Screen Shot 2019-10-31 at 13 39 14](https://user-images.githubusercontent.com/38926265/67984396-d9b24e00-fbe3-11e9-8630-1195121a7a37.png)

**Comment by el-guero-mero** [comment]
I got it to work properly, I had to manually specify port 4200 on the "node server.js" command to get the routing to work properly ;) Thank you.

**Comment by wingkee98** [comment]
Hi Mateo,
You don't need to manually specified any port number when run node server.js from console. Once the service is running, just simply point your browser to localhost:9000.
Anyhow, you had it worked. 
Thank you.
    On Thursday, October 31, 2019, 01:47:40 PM PDT, Mateo Nares <notifications@github.com> wrote:  
 
 
Closed #1.
